<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobPostingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs = [
            [
                'initials' => 'TN',
                'color' => '#1e3a4f',
                'title' => 'Senior Frontend Developer',
                'company' => 'TechNova',
                'location' => 'San Francisco, CA',
                'time_ago' => '2d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['React', 'TypeScript', 'Tailwind CSS']),
                'salary' => '$120k-$160k',
                'description' => "Join TechNova to lead the frontend architecture of our next-gen data platform. We're looking for a Senior React Developer who obsesses over clean code.",
                'what_youll_do' => json_encode(['Architect reusable React components', 'Set frontend best practices', 'Work directly with Design']),
                'why_company' => json_encode(['High Growth: zero legacy code', '100% remote-first', 'Equity and full benefits']),
            ],
            [
                'initials' => 'DS',
                'color' => '#7EB0AB',
                'title' => 'Backend Engineer',
                'company' => 'DataStream',
                'location' => 'New York, NY',
                'time_ago' => '3d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Node.js', 'PostgreSQL', 'AWS']),
                'salary' => '$130k-$170k',
                'description' => "Build robust, scalable APIs that power real-time data pipelines using Node.js and PostgreSQL.",
                'what_youll_do' => json_encode(['Design RESTful and GraphQL APIs', 'Optimize database queries', 'Collaborate with DevOps']),
                'why_company' => json_encode(['Process millions of events', 'Dedicated learning budget', 'Comprehensive benefits']),
            ],
            [
                'initials' => 'CH',
                'color' => '#1e3a4f',
                'title' => 'UX/UI Designer',
                'company' => 'CreativeHub',
                'location' => 'Remote',
                'time_ago' => '4d ago',
                'type' => 'Contract',
                'tags' => json_encode(['Figma', 'User Research', 'Prototyping']),
                'salary' => '$90k-$120k',
                'description' => "Craft intuitive and visually stunning interfaces. Lead user research and create wireframes in Figma.",
                'what_youll_do' => json_encode(['Conduct usability testing', 'Create high-fidelity mockups', 'Ensure design fidelity']),
                'why_company' => json_encode(['Creative Freedom', 'Remote-First', 'Performance bonuses']),
            ],
            [
                'initials' => 'CS',
                'color' => '#2a5a6e',
                'title' => 'DevOps Engineer',
                'company' => 'CloudScale',
                'location' => 'Austin, TX',
                'time_ago' => '5d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Kubernetes', 'Docker', 'Terraform']),
                'salary' => '$140k-$180k',
                'description' => "Build and maintain cloud infrastructure with Kubernetes and Terraform to ensure 99.99% uptime.",
                'what_youll_do' => json_encode(['Design CI/CD pipelines', 'Monitor cloud infrastructure', 'Implement IaC']),
                'why_company' => json_encode(['Manage scale for 50M+ users', 'Strong engineering culture', 'Stock options']),
            ],
            [
                'initials' => 'AX',
                'color' => '#6366f1',
                'title' => 'Mobile Developer (React Native)',
                'company' => 'AppAxis',
                'location' => 'Los Angeles, CA',
                'time_ago' => '1d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['React Native', 'TypeScript', 'iOS', 'Android']),
                'salary' => '$110k-$150k',
                'description' => "Own the full mobile stack from UI to deployment on both iOS and Android stores.",
                'what_youll_do' => json_encode(['Maintain cross-platform apps', 'Integrate third-party SDKs', 'Manage App Store releases']),
                'why_company' => json_encode(['5M+ active users', 'Greenfield React Native', 'Wellness stipend']),
            ],
            [
                'initials' => 'NL',
                'color' => '#0ea5e9',
                'title' => 'Data Scientist',
                'company' => 'NeuraLabs',
                'location' => 'Boston, MA',
                'time_ago' => '1d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Python', 'Machine Learning', 'TensorFlow']),
                'salary' => '$135k-$175k',
                'description' => "Build predictive models and drive data-informed product decisions using state-of-the-art ML.",
                'what_youll_do' => json_encode(['Deploy ML models', 'Analyze large datasets', 'Collaborate with Product']),
                'why_company' => json_encode(['Publish research papers', 'GPU cluster access', 'Research bonus']),
            ],
            [
                'initials' => 'PH',
                'color' => '#1e3a4f',
                'title' => 'Product Manager',
                'company' => 'PivotHub',
                'location' => 'Remote',
                'time_ago' => '6h ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Product Strategy', 'Agile', 'Analytics']),
                'salary' => '$115k-$155k',
                'description' => "Lead cross-functional teams and drive the product roadmap. Define strategy and prioritize features.",
                'what_youll_do' => json_encode(['Define product vision', 'Ship features on time', 'Analyze product metrics']),
                'why_company' => json_encode(['Full autonomy', 'Async culture', 'Quarterly retreats']),
            ],
            [
                'initials' => 'SG',
                'color' => '#ef4444',
                'title' => 'QA Engineer',
                'company' => 'ShieldGuard',
                'location' => 'Chicago, IL',
                'time_ago' => '3d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Selenium', 'Cypress', 'API Testing']),
                'salary' => '$85k-$115k',
                'description' => "Ensure reliability and security of fintech platform using automated end-to-end testing.",
                'what_youll_do' => json_encode(['Design test plans', 'Maintain automated suites', 'Identify defects']),
                'why_company' => json_encode(['Protect financial transactions', 'Clear career path', 'Annual bonus']),
            ],
            [
                'initials' => 'FL',
                'color' => '#7EB0AB',
                'title' => 'Full-Stack Developer',
                'company' => 'FlowLabs',
                'location' => 'Seattle, WA',
                'time_ago' => '12h ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Next.js', 'Node.js', 'MongoDB']),
                'salary' => '$125k-$165k',
                'description' => "Build end-to-end features across SaaS platform using Next.js and MongoDB.",
                'what_youll_do' => json_encode(['Build features DB to UI', 'Optimize MongoDB schemas', 'Architectural decisions']),
                'why_company' => json_encode(['Modern Stack (Next.js 14)', 'High ownership', 'Unlimited PTO']),
            ],
            [
                'initials' => 'VP',
                'color' => '#8b5cf6',
                'title' => 'Technical Writer',
                'company' => 'VerbPro',
                'location' => 'Remote',
                'time_ago' => '2d ago',
                'type' => 'Contract',
                'tags' => json_encode(['Documentation', 'API Docs', 'Markdown']),
                'salary' => '$70k-$95k',
                'description' => "Create clear, developer-friendly documentation, guides, and tutorials for API platform.",
                'what_youll_do' => json_encode(['Maintain API references', 'Create onboarding content', 'Work with engineering']),
                'why_company' => json_encode(['Huge developer audience', 'Async-first workflow', 'Contract renewal options']),
            ],
            [
                'initials' => 'BF',
                'color' => '#f59e0b',
                'title' => 'Cybersecurity Analyst',
                'company' => 'ByteFortress',
                'location' => 'Washington, DC',
                'time_ago' => '4d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Security', 'SIEM', 'Penetration Testing']),
                'salary' => '$100k-$140k',
                'description' => "Protect critical infrastructure through threat analysis and penetration testing.",
                'what_youll_do' => json_encode(['Analyze security events', 'Conduct vulnerability tests', 'Develop incident plans']),
                'why_company' => json_encode(['Protect gov systems', 'Sponsors clearance', 'Clearance bonus']),
            ],
            [
                'initials' => 'GW',
                'color' => '#2a5a6e',
                'title' => 'Game Developer (Unity)',
                'company' => 'GridWorks',
                'location' => 'San Diego, CA',
                'time_ago' => '1w ago',
                'type' => 'Full-time',
                'tags' => json_encode(['Unity', 'C#', '3D Graphics']),
                'salary' => '$95k-$130k',
                'description' => "Create immersive 3D experiences. Build gameplay systems and optimize rendering.",
                'what_youll_do' => json_encode(['Develop mechanics in C#', 'Optimize 3D performance', 'Work with artists']),
                'why_company' => json_encode(['Original IP work', 'Latest Unity LTS', 'Profit sharing']),
            ],
            [
                'initials' => 'EM',
                'color' => '#0d9488',
                'title' => 'Marketing Analyst',
                'company' => 'EchoMetrics',
                'location' => 'Miami, FL',
                'time_ago' => '5d ago',
                'type' => 'Part-time',
                'tags' => json_encode(['SQL', 'Google Analytics', 'Tableau']),
                'salary' => '$55k-$75k',
                'description' => "Turn campaign data into insights. Build dashboards and run A/B tests.",
                'what_youll_do' => json_encode(['Build Tableau dashboards', 'Analyze performance', 'Run A/B tests']),
                'why_company' => json_encode(['Data-driven decisions', 'Flexible schedule', 'Performance bonuses']),
            ],
            [
                'initials' => 'SF',
                'color' => '#1e3a4f',
                'title' => 'Solutions Architect',
                'company' => 'StackForge',
                'location' => 'Denver, CO',
                'time_ago' => '3d ago',
                'type' => 'Full-time',
                'tags' => json_encode(['AWS', 'System Design', 'Microservices']),
                'salary' => '$150k-$200k',
                'description' => "Design scalable cloud architectures and lead technical discovery for enterprise clients.",
                'what_youll_do' => json_encode(['Document cloud-native arch', 'Lead discovery sessions', 'Guide engineering teams']),
                'why_company' => json_encode(['Senior leadership role', 'Work across industries', 'Consulting bonuses']),
            ],
            [
                'initials' => 'PS',
                'color' => '#ec4899',
                'title' => 'Graphic Designer',
                'company' => 'PixelShift',
                'location' => 'Remote',
                'time_ago' => '6d ago',
                'type' => 'Contract',
                'tags' => json_encode(['Photoshop', 'Illustrator', 'Branding']),
                'salary' => '$60k-$85k',
                'description' => "Create visual assets for tech startups including branding and social media graphics.",
                'what_youll_do' => json_encode(['Design brand identities', 'Create marketing ads', 'Iterate with clients']),
                'why_company' => json_encode(['Work with startup brands', 'Creative freedom', 'Extension options']),
            ],
        ];

        foreach ($jobs as $job) {
            DB::table('job_postings')->insert(array_merge($job, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}